version: '3.9'

services:

  gateway:
    build:
      context: ./
    container_name: gateway
    env_file:
      - .env
    ports:
      - "5000:5000"
    networks:
      - common_network
   
networks:
  common_network:
    external: true