FROM python:3.11-slim-buster
WORKDIR /src

COPY . /src

RUN pip install -r requirements.txt

EXPOSE 5000

COPY ./entrypoint-heroku.sh .

RUN chmod +x ./entrypoint-heroku.sh

CMD ["./entrypoint-heroku.sh"]